force-app/main/default/objects/breadwinner_qbo__Invoice__c/fields/CRN_Number__c.field-meta.xml
<CustomField>
    <fullName>CRN_Number__c</fullName>
    <label>CRN Number</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRN_Number__c/CRN_Number__c.object-meta.xml
<CustomObject>
    <label>CRN Number</label>
    <nameField>
        <displayFormat>CRN-{0000}</displayFormat>
        <label>CRN Number Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>CRN Numbers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CRN_Number__c/fields/CRN_Utilize__c.field-meta.xml
<CustomField>
    <fullName>CRN_Utilize__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This will show that CRN Number is utilized or not.</description>
    <label>CRN Utilize</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CRN_Number__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/InvoicePDFCtrlTest.cls
@IsTest(SeeAllData=true)
public class InvoicePDFCtrlTest {
    @IsTest static void InvoicePDFCtrlTest(){
        Test.startTest();
            breadwinner_qbo__Invoice__c NewInvoice = new breadwinner_qbo__Invoice__c();
            NewInvoice.Name = 'Testing Invoice';
            Newinvoice.breadwinner_qbo__Billing_Street_Address__c = 'testing address';
            Insert NewInvoice;
            
            CRN_Number__c crntest = new CRN_Number__c();
            crntest.Number__c = 'CRN-3355';
        	crntest.CRN_Utilize__c = false;
            Insert crntest;
        
            PageReference pageRef = Page.InvoicePDF;
            Test.setCurrentPage(pageRef);
            pageRef.getParameters().put('id',NewInvoice.Id);
            
            ApexPages.StandardController sc = new ApexPages.StandardController(NewInvoice);
            InvoicePDFCtrl Ipc = new InvoicePDFCtrl(sc);
        Test.stopTest();
    }
}