force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Azurite Booking Form submitted on Azurite website.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/End_Date_2__c.field-meta.xml
<CustomField>
    <fullName>End_Date_2__c</fullName>
    <label>End Date 2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Date_2__c.field-meta.xml
<CustomField>
    <fullName>Start_Date_2__c</fullName>
    <label>Start Date 2</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/PackageCalculatorCtlr.cls
public with sharing class PackageCalculatorCtlr {
    
    @AuraEnabled
    public static void saveDates(String startDate, String StartDate2, String endDate, String endDate2, String recordId){
        try{
            if(recordId != null && !String.isEmpty(recordId)){
                
            }
            Booking__c booking = new Booking__c();
            booking.Id = recordId;
            booking.Start_Date__c = Date.valueOf(startDate);
            booking.Start_Date_2__c = Date.valueOf(StartDate2);
            booking.End_Date__c = Date.valueOf(endDate);
            booking.End_Date_2__c = Date.valueOf(endDate2);
            
            update booking;
            
        }catch (Exception e){
            throw new AuraHandledException(e.getMessage());
        } 
    }
}