force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Azurite Booking Form submitted on Azurite website.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Desired_Implants__c.field-meta.xml
<CustomField>
    <fullName>Desired_Implants__c</fullName>
    <label>Desired Implants?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saline</fullName>
            </value>
            <value>
                <fullName>Silicone Gel</fullName>
            </value>
            <value>
                <fullName>Unsure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Desired_implants__c.field-meta.xml
<CustomField>
    <fullName>Desired_implants__c</fullName>
    <label>Desired implants</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Armpits</fullName>
            </value>
            <value>
                <fullName>Under Breast Crease</fullName>
            </value>
            <value>
                <fullName>Lower edge of Areola</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateUploadFlagOnBookingTest.cls
@isTest(SeeAllData=false)
public class UpdateUploadFlagOnBookingTest {
	
    public static testmethod void TestUpdateUploadFlagOnBooking(){
        test.startTest();
            Contact con = new Contact();
            con.FirstName = 'Test';
            con.LastName = 'Contact';
            insert con;
            
            Booking__c TestBooking = new Booking__c();
            TestBooking.Name = 'New Booking[Test Booking]';
            TestBooking.Contact__c = con.Id;
        	TestBooking.Desired_Implants__c = 'Saline';
            Insert TestBooking;
        	
        	VisaTest(TestBooking.Id);
        	medicalTest(TestBooking.Id);
        	passportTest(TestBooking.Id);
        	flightTest(TestBooking.Id);
        	waiverTest(TestBooking.Id);
        	
        test.stopTest();
    }
    
    public static void VisaTest(String Id){
        List<String> testString = new List<String>{Id +'-'+'visa'};
        UpdateUploadFlagOnBooking.updateFlag(testString);
    }
    public static void medicalTest(String Id){
        List<String> testString = new List<String>{Id +'-'+'medical'};
        UpdateUploadFlagOnBooking.updateFlag(testString);
    }
    public static void passportTest(String Id){
        List<String> testString = new List<String>{Id +'-'+'passport'};
        UpdateUploadFlagOnBooking.updateFlag(testString);
    }
    public static void flightTest(String Id){
        List<String> testString = new List<String>{Id +'-'+'flight'};
        UpdateUploadFlagOnBooking.updateFlag(testString);
    }
    public static void waiverTest(String Id){
        List<String> testString = new List<String>{Id +'-'+'waiver'};
        UpdateUploadFlagOnBooking.updateFlag(testString);
    }
}