force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Azurite Booking Form submitted on Azurite website.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Is_Flight_info_uploaded__c.field-meta.xml
<CustomField>
    <fullName>Is_Flight_info_uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Flight info uploaded?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Is_medical_uploaded__c.field-meta.xml
<CustomField>
    <fullName>Is_medical_uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is medical uploaded?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Is_passport_uploaded__c.field-meta.xml
<CustomField>
    <fullName>Is_passport_uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is passport uploaded?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Is_visa_uploaded__c.field-meta.xml
<CustomField>
    <fullName>Is_visa_uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is visa uploaded?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Is_waiver_uploaded__c.field-meta.xml
<CustomField>
    <fullName>Is_waiver_uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is waiver uploaded?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/UpdateUploadFlagOnBooking.cls
global without sharing class UpdateUploadFlagOnBooking {
    @InvocableMethod
    public static void updateFlag(List<String> param) {
        String recordId = param[0].split('-')[0];
        String field = param[0].split('-')[1];
        Booking__c booking = new Booking__c(Id = recordId);
        if(field == 'visa')				booking.Is_visa_uploaded__c = true;
        else if(field == 'medical')		booking.Is_medical_uploaded__c = true;
        else if(field == 'passport')	booking.Is_passport_uploaded__c = true;
        else if(field == 'flight')		booking.Is_Flight_Info_uploaded__c = true;
        else if(field == 'waiver')      booking.is_waiver_uploaded__c = true;
        update booking;
    }
}