force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Age_of_youngest_child__c.field-meta.xml
<CustomField>
    <fullName>Age_of_youngest_child__c</fullName>
    <label>Age of youngest child</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Are_you_on_birth_control__c.field-meta.xml
<CustomField>
    <fullName>Are_you_on_birth_control__c</fullName>
    <label>Are you on birth control?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Are_you_planning_for_more_pregnancies__c.field-meta.xml
<CustomField>
    <fullName>Are_you_planning_for_more_pregnancies__c</fullName>
    <label>Are you planning for more pregnancies?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Are_you_pregnant_now__c.field-meta.xml
<CustomField>
    <fullName>Are_you_pregnant_now__c</fullName>
    <label>Are you pregnant now?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>yes</fullName>
            </value>
            <value>
                <fullName>no</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Current_bra_size__c.field-meta.xml
<CustomField>
    <fullName>Current_bra_size__c</fullName>
    <label>Current bra size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Desired_bra_size__c.field-meta.xml
<CustomField>
    <fullName>Desired_bra_size__c</fullName>
    <label>Desired bra size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Desired_implants__c.field-meta.xml
<CustomField>
    <fullName>Desired_implants__c</fullName>
    <label>Desired implants</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Armpits</fullName>
            </value>
            <value>
                <fullName>Under Breast Crease</fullName>
            </value>
            <value>
                <fullName>Lower edge of Areola</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Desired_incision__c.field-meta.xml
<CustomField>
    <fullName>Desired_incision__c</fullName>
    <label>Desired incision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Armpits</fullName>
            </value>
            <value>
                <fullName>Under Breast Crease</fullName>
            </value>
            <value>
                <fullName>Lower edge of Areola</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Desired_placement_of_implants__c.field-meta.xml
<CustomField>
    <fullName>Desired_placement_of_implants__c</fullName>
    <label>Desired placement of implants</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Behind muscle</fullName>
            </value>
            <value>
                <fullName>Front of muscle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Do_you_have_breast_implants__c.field-meta.xml
<CustomField>
    <fullName>Do_you_have_breast_implants__c</fullName>
    <label>Do you have breast implants</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/If_YES_please_specify_method__c.field-meta.xml
<CustomField>
    <fullName>If_YES_please_specify_method__c</fullName>
    <label>If YES please specify method</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Passport_Country__c.field-meta.xml
<CustomField>
    <fullName>Passport_Country__c</fullName>
    <label>Passport Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Age_of_youngest_child__c.field-meta.xml
<CustomField>
    <fullName>Age_of_youngest_child__c</fullName>
    <inlineHelpText>Number of Years.</inlineHelpText>
    <label>Age of youngest child</label>
    <precision>4</precision>
    <scale>1</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Alternate_Date_of_Surgery__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Date_of_Surgery__c</fullName>
    <label>Alternate Date of Surgery</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Are_you_on_birth_control__c.field-meta.xml
<CustomField>
    <fullName>Are_you_on_birth_control__c</fullName>
    <label>Are you on birth control?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Are_you_pregnant_now__c.field-meta.xml
<CustomField>
    <fullName>Are_you_pregnant_now__c</fullName>
    <label>Are you pregnant now?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Desired_implants__c.field-meta.xml
<CustomField>
    <fullName>Desired_implants__c</fullName>
    <label>Desired implants?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saline</fullName>
            </value>
            <value>
                <fullName>Silicone Gel</fullName>
            </value>
            <value>
                <fullName>Unsure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Desired_incision__c.field-meta.xml
<CustomField>
    <fullName>Desired_incision__c</fullName>
    <label>Desired incision?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Armpits</fullName>
            </value>
            <value>
                <fullName>Under Breast Crease</fullName>
            </value>
            <value>
                <fullName>Lower edge of Areola</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Desired_placement_of_implants__c.field-meta.xml
<CustomField>
    <fullName>Desired_placement_of_implants__c</fullName>
    <label>Desired placement of implants?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Behind of muscle</fullName>
            </value>
            <value>
                <fullName>In-front of muscle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Do_you_have_breast_implants__c.field-meta.xml
<CustomField>
    <fullName>Do_you_have_breast_implants__c</fullName>
    <label>Do you have breast implants?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Emergency_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_Phone__c</fullName>
    <label>Emergency Contact Phone</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Have_you_had_a_mammogram__c.field-meta.xml
<CustomField>
    <fullName>Have_you_had_a_mammogram__c</fullName>
    <label>Have you had a mammogram?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/HRT_Medications_Hormone_Patch__c.field-meta.xml
<CustomField>
    <fullName>HRT_Medications_Hormone_Patch__c</fullName>
    <label>HRT Medications/Hormone Patch</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Last_breastfed_on_date__c.field-meta.xml
<CustomField>
    <fullName>Last_breastfed_on_date__c</fullName>
    <label>Last breastfed on (date)?</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Please_specify_results_patients_over_40__c.field-meta.xml
<CustomField>
    <fullName>Please_specify_results_patients_over_40__c</fullName>
    <label>Please specify results(patients over 40)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Preferred_Date_of_Surgery__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Date_of_Surgery__c</fullName>
    <label>Preferred Date of Surgery</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Procedure_Type__c.field-meta.xml
<CustomField>
    <fullName>Procedure_Type__c</fullName>
    <label>Procedure Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Dental Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Procedures_Requested__c.field-meta.xml
<CustomField>
    <fullName>Procedures_Requested__c</fullName>
    <label>Procedures Requested</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Travel_Companion_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Travel_Companion_Date_of_Birth__c</fullName>
    <label>Travel Companion Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Travel_Companion_First_Name__c.field-meta.xml
<CustomField>
    <fullName>Travel_Companion_First_Name__c</fullName>
    <label>Travel Companion First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Travel_Companion_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Travel_Companion_Last_Name__c</fullName>
    <label>Travel Companion Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/LeadConverterCtrlTest.cls
@isTest(SeeAllData=false)
public class LeadConverterCtrlTest {
	
    static testMethod void LeadConvertTest(){
        test.startTest();
        	// * Create Lead
        	// * Trigger automatically leadconevrt trigger
        	// ======== >>> Lead Generation  <<< ===========
        		CreateLead('Test123@gmail.com');
        	// =============================================
        test.stopTest();
    }
    
    static testMethod void LeadConvertTest2(){
        
        Account acc = new Account();
        acc.Name = 'New Account[James Davaid]';
        acc.BillingCity = 'Glasgow';
        acc.BillingPostalCode = '00125';
        acc.Website = 'https://www.test.com';
        Insert acc;
        	
        	Contact con = new Contact();
        	con.FirstName = 'Test';
        	con.LastName = 'Contact';
        	con.Email = 'Test123@gmail.com';
        	con.AccountId = acc.Id;
        	Insert con;
        
        	CreateLead(con.Email);
    }
    
    static testmethod void LeadConvertTest3(){
        Contact con = new Contact();
        	con.FirstName = 'Test';
        	con.LastName = 'Contact';
        	con.Email = 'Test123@gmail.com';
        	Insert con;
        	CreateLead(con.Email);
        
    }
    
    
    
    public static void CreateLead(String ConEmail){
        Lead ld = new Lead();
        		ld.FirstName = 'James';
        		ld.LastName = 'Davaid';
        		ld.Passport_Country__c = 'United Kingdom';
        		ld.Date_of_Birth__c = Date.newInstance(1993, 04, 8);
        		ld.Gender__c = 'Male';
        		ld.Street = '83 High Street KILMARNOCK KA46 9QW';
        		ld.City = 'Glasgow';
        		ld.State = 'Wales';
        		ld.Website = 'https://www.test.com';
        		ld.PostalCode = '00125';
        		ld.Country = 'United Kingdom';
        		ld.Email = ConEmail;
        		ld.Phone = '+9231312345';
        		ld.Preferred_Date_of_Surgery__c = Date.newInstance(2019, 11, 26);
        		ld.Alternate_Date_of_Surgery__c = Date.newInstance(2019, 11, 28);
        		ld.Procedure_Type__c = 'General';
        		ld.Procedures_Requested__c = 'Test procedure requested';
        		ld.Travel_Companion_First_Name__c = 'James';
        		ld.Travel_Companion_Last_Name__c = 'Brown';
        		ld.Travel_Companion_Date_of_Birth__c = Date.newInstance(1994, 08, 14);
        		ld.Emergency_Contact_Phone__c = '+923135290107';
        		ld.Emergency_Contact_Name__c = 'Bruice Wilson';
        		ld.Do_you_have_breast_implants__c = 'Yes';
        		ld.If_YES_please_specify_method__c = 'Test method applied';
        		ld.Are_you_on_birth_control__c = 'No';
        		ld.HRT_Medications_Hormone_Patch__c = 'Yes';
        		ld.Age_of_youngest_child__c = 14;
        		ld.Current_bra_size__c = '32';
        		ld.Desired_bra_size__c = '16';
        		ld.Desired_placement_of_implants__c = 'In-front of muscle';
        		ld.Desired_implants__c = 'Saline';
        		ld.Desired_incision__c = 'Armpits';
        		ld.Have_you_had_a_mammogram__c = 'Yes';
        		ld.Please_specify_results_patients_over_40__c = '20';
        		ld.Are_you_pregnant_now__c = 'No';
        		ld.Are_you_planning_for_more_pregnancies__c = 'No';
        		ld.Last_breastfed_on_date__c = Date.newInstance(2019, 11, 03);
        		ld.Company = 'Women Trust Industries';
        		ld.LeadSource = 'Community Booking';
        		Insert ld;
    }
    
    
}