force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Azurite Booking Form submitted on Azurite website.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings (Doctor)</relationshipLabel>
    <relationshipName>Doctor_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/About__c.field-meta.xml
<CustomField>
    <fullName>About__c</fullName>
    <label>About</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Passport_Country__c.field-meta.xml
<CustomField>
    <fullName>Passport_Country__c</fullName>
    <label>Passport Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profile_Picture__c.field-meta.xml
<CustomField>
    <fullName>Profile_Picture__c</fullName>
    <inlineHelpText>Id of the document in Profile pictures folder</inlineHelpText>
    <label>Profile Picture</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <label>Doctor</label>
</RecordType>

force-app/main/default/classes/CreatePayableCtrlTest.cls
@IsTest
public class CreatePayableCtrlTest {
    @IsTest static void CreatePayableCtrltest(){
        Test.startTest();
        	
            Account NewTestAccount = New Account();
            NewTestAccount.Name = 'Testing Account';
            NewTestAccount.Phone = '+923135290107';
            NewTestAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
            Insert NewTestAccount;
        
        	Contact NewTestContact = new Contact();
            NewTestContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
            NewTestContact.FirstName = 'Test';
            NewTestContact.LastName = 'Contact';
            NewTestContact.Passport_Country__c = 'Pakistan';
            NewTestContact.Gender__c = 'Male';
            NewTestContact.Birthdate = System.today();
            NewTestContact.Phone = '923135290107';
            NewTestContact.Email = 'fahad.munawar.khan@gmail.com';
            NewTestContact.About__c = 'This is testing about information';
            NewTestContact.Profile_Picture__c = '015O0000003CMEi';
        	NewTestContact.AccountId = NewTestAccount.Id;
            Insert NewTestContact;
        
        	Contact NewTestDoctor = new Contact();
            NewTestDoctor.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Doctor').getRecordTypeId();
            NewTestDoctor.FirstName = 'Testing new';
            NewTestDoctor.LastName = 'Contact';
            NewTestDoctor.Passport_Country__c = 'Pakistan';
            NewTestDoctor.Gender__c = 'Male';
            NewTestDoctor.Birthdate = System.today();
            NewTestDoctor.Phone = '923135290107';
            NewTestDoctor.Email = 'test@gmail.com';
            NewTestDoctor.About__c = 'This is testing about information';
            NewTestDoctor.Profile_Picture__c = '015O0000003CMEi';
        	NewTestDoctor.AccountId = NewTestAccount.Id;
            Insert NewTestDoctor;
        
        	Booking__c NewTestBooking = new Booking__c();
        	NewTestBooking.Name = 'New Booking__['+NewTestContact.FirstName+' '+NewTestContact.LastName+']';
        	NewTestBooking.Status__c = 'Open';
        	NewTestBooking.Contact__c = NewTestContact.Id;
        	NewTestBooking.Doctor__c = NewTestDoctor.Id;
        	Insert NewTestBooking;
        
        	CreatePayableCtrl.GetPayable(NewTestBooking.Id);
        Test.stopTest();
    }
}