force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Azurite Booking Form submitted on Azurite website.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Dental__c.field-meta.xml
<CustomField>
    <fullName>Dental__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dental</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Dentist</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings (Dental)</relationshipLabel>
    <relationshipName>Bookings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Dentist_Time__c.field-meta.xml
<CustomField>
    <fullName>Dentist_Time__c</fullName>
    <label>Dentist Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings (Doctor)</relationshipLabel>
    <relationshipName>Doctor_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Hospital__c.field-meta.xml
<CustomField>
    <fullName>Hospital__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will display that user booked which hospital.</description>
    <inlineHelpText>Please select hospital.</inlineHelpText>
    <label>Hospital</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Hospital</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Personal_Assistant__c.field-meta.xml
<CustomField>
    <fullName>Personal_Assistant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personal Assistant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Personal Assistant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings (Personal Assistant)</relationshipLabel>
    <relationshipName>Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Procedures_Requested_Please_Specify__c.field-meta.xml
<CustomField>
    <fullName>Procedures_Requested_Please_Specify__c</fullName>
    <label>Procedures Requested (Please Specify)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Service__c.field-meta.xml
<CustomField>
    <fullName>Service__c</fullName>
    <label>Service</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <summarizedField>Session__c.Session_days__c</summarizedField>
    <summaryForeignKey>Session__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Medical_Balance__c.field-meta.xml
<CustomField>
    <fullName>Total_Medical_Balance__c</fullName>
    <label>Total Medical Balance</label>
    <summarizedField>Session__c.Medical_Balance__c</summarizedField>
    <summaryForeignKey>Session__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Contact/fields/About__c.field-meta.xml
<CustomField>
    <fullName>About__c</fullName>
    <label>About</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Hospital_Balance__c.field-meta.xml
<CustomField>
    <fullName>Hospital_Balance__c</fullName>
    <label>Hospital Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Procedures_Requested_Please_Specify__c.field-meta.xml
<CustomField>
    <fullName>Procedures_Requested_Please_Specify__c</fullName>
    <label>Procedures Requested (Please Specify)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profile_Picture__c.field-meta.xml
<CustomField>
    <fullName>Profile_Picture__c</fullName>
    <inlineHelpText>Id of the document in Profile pictures folder</inlineHelpText>
    <label>Profile Picture</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <description>This object is for doctor session. This object will save record of Azurite start date and end date.</description>
    <label>Surgery Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surgery Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Surgery Sessions</relationshipLabel>
    <relationshipName>Surgery_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Date on which Azurite session is end.</inlineHelpText>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Hospital__c.field-meta.xml
<CustomField>
    <fullName>Hospital__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hospital</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surgery Sessions</relationshipLabel>
    <relationshipName>Surgery_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Medical_Balance__c.field-meta.xml
<CustomField>
    <fullName>Medical_Balance__c</fullName>
    <label>Medical Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Procedures__c.field-meta.xml
<CustomField>
    <fullName>Procedures__c</fullName>
    <label>Procedures</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Session_days__c.field-meta.xml
<CustomField>
    <fullName>Session_days__c</fullName>
    <formula>End_Date__c -  Start_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Session days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Date on which azurite session is start.</inlineHelpText>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/MyJourneyCtrl.cls
public without sharing class MyJourneyCtrl {
	@AuraEnabled
    Public static Booking__c GetBooking(String UserId){
		Booking__c BookingInfo = [SELECT Id, 
                                  Name, 
                                  createdDate, 
                                  Procedures_Requested_Please_Specify__c,
                                  Personal_Assistant__r.FirstName, 
                                  Personal_Assistant__r.LastName,
                                  Personal_Assistant__r.About__c,
                                  Personal_Assistant__r.Profile_Picture__c, 
                                  Dental__r.Account.BillingStreet,
                                  Dental__r.Account.BillingCity,
                                  Dental__r.Account.BillingCountry,
                                  Dentist_Time__c,
                                  Service__c,
                                  Contact__r.Hospital_Balance__c,
                                  Total_Medical_Balance__c
                                  FROM booking__c where contact__c in (SELECT contactId from user where Id =: UserId) order by createdDate desc limit 1];
        return BookingInfo;
    }
    
    @AuraEnabled
    public static Map<String, List<Session__c>> GetSessions(String BookId){
        system.debug('BookId : '+BookId);
        List<Session__c> Sessions = new List<Session__c>();
        Map<String, List<Session__c>> NewSess = new Map<String, List<Session__c>>();
        Sessions = [SELECT Id, Name, 
                    CreatedDate,
                    Procedures__c,
                    Medical_Balance__c,
                    Doctor__r.FirstName,
                    Doctor__r.LastName,
                    Doctor__r.About__c,
                    Doctor__r.Profile_Picture__c,
                    Start_Date__c,
                    End_Date__c,
                    Hospital__r.Name,
                    Hospital__r.BillingStreet, 
                    Hospital__r.BillingCity, 
                    Hospital__r.BillingCountry,
                    Session_days__c,
                    CurrencyISOCode
                    FROM Session__c WHERE Booking__r.Id =: BookId order by createdDate ASC];
		NewSess.put('FirstLog', Sessions);
        return NewSess;
    }
    
    
    @AuraEnabled
    public static List<Id> GetAttachments(String BookingId){
        list<Id> attachmentId = new List<Id>();
        List<Id> ContentVersionIds = new List<Id>();
        for(ContentDocumentLink conts : [SELECT Id, ContentDocumentId FROM ContentDocumentLink WHERE LinkedEntityId =: BookingId]){
            attachmentId.add(conts.ContentDocumentId);
        }
        system.debug(attachmentId);
        for(ContentVersion ConverIds : [select id from contentversion where contentdocumentid IN : attachmentId  AND (FileType = 'PNG' OR FileType = 'JPG' OR FileType = 'JPEG' OR FileType = 'png' OR FileType = 'jpg' OR FileType = 'jpeg')]){
            ContentVersionIds.add(ConverIds.Id);
        }
        return ContentVersionIds;
    }
}