force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Azurite Booking Form submitted on Azurite website.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings (Doctor)</relationshipLabel>
    <relationshipName>Doctor_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <summarizedField>Session__c.Session_days__c</summarizedField>
    <summaryForeignKey>Session__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/About__c.field-meta.xml
<CustomField>
    <fullName>About__c</fullName>
    <label>About</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Passport_Country__c.field-meta.xml
<CustomField>
    <fullName>Passport_Country__c</fullName>
    <label>Passport Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profile_Picture__c.field-meta.xml
<CustomField>
    <fullName>Profile_Picture__c</fullName>
    <inlineHelpText>Id of the document in Profile pictures folder</inlineHelpText>
    <label>Profile Picture</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <label>Doctor</label>
</RecordType>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <description>This object is for doctor session. This object will save record of Azurite start date and end date.</description>
    <label>Surgery Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surgery Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Surgery Sessions</relationshipLabel>
    <relationshipName>Surgery_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Date on which Azurite session is end.</inlineHelpText>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Medical_Balance__c.field-meta.xml
<CustomField>
    <fullName>Medical_Balance__c</fullName>
    <label>Medical Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Date on which azurite session is start.</inlineHelpText>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/MyJourneyCtrlTest.cls
@isTest
public class MyJourneyCtrlTest {
	public static testmethod void testMyJourneyCtrl()
    {
        test.startTest();
        User u = testUtils.createCommunityUser(true);
        Booking__c book = TestUtils.createBooking(true, u.ContactId);
        
        
        
        Booking__c theBooking = MyJourneyCtrl.GetBooking(u.Id);
        
        Account NewTestAccountDoc = New Account();
        NewTestAccountDoc.Name = 'Testing Account Doc';
        NewTestAccountDoc.Phone = '+923135290107';
        NewTestAccountDoc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        Insert NewTestAccountDoc;
        
        Contact NewTestContactDoc = new Contact();
        NewTestContactDoc.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Doctor').getRecordTypeId();
        NewTestContactDoc.FirstName = 'Test Doctor';
        NewTestContactDoc.LastName = 'Contact 2';
        NewTestContactDoc.Passport_Country__c = 'Pakistan';
        NewTestContactDoc.Gender__c = 'Male';
        NewTestContactDoc.Birthdate = System.today();
        NewTestContactDoc.Phone = '923135290107';
        NewTestContactDoc.Email = 'testing2@gmail.com';
        NewTestContactDoc.About__c = 'This is testing about information';
        NewTestContactDoc.Profile_Picture__c = '015O0000003CMEi';
        NewTestContactDoc.AccountId = NewTestAccountDoc.Id;
        Insert NewTestContactDoc;
        
        List<Session__c> sesstocheck = new List<Session__c>();
        for(Integer i=0; i<4; i++){
            Session__c testsess = new Session__c();
            testsess.Start_Date__c = system.today()+i;
            testsess.End_Date__c = system.today()+i+1;
            testsess.Doctor__c = NewTestContactDoc.Id;
            testsess.Booking__c = theBooking.Id;
            testsess.Medical_Balance__c = 120+i;
            sesstocheck.add(testsess);
        }
        Insert sesstocheck;
        CreateAttachments(theBooking.Id);
        MyJourneyCtrl.GetAttachments(theBooking.Id);
        MyJourneyCtrl.GetSessions(theBooking.Id);
        test.stopTest();
    }
    
    
    public static void CreateAttachments(String parentId){
        
        Blob beforeblob=Blob.valueOf('Unit Test Attachment Body');
        ContentVersion cv = new ContentVersion();
        cv.title = 'test content trigger';      
        cv.PathOnClient ='test';           
        cv.VersionData =beforeblob;          
        insert cv;         
        
        ContentVersion testContent = [SELECT id, ContentDocumentId FROM ContentVersion where Id = :cv.Id];
        
        ContentDocumentLink contentlink=new ContentDocumentLink();
        contentlink.LinkedEntityId= parentId;
        contentlink.ShareType= 'V';
        contentlink.ContentDocumentId = testContent.ContentDocumentId;
        contentlink.Visibility = 'AllUsers'; 
        insert contentlink;
    }
}