force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Azurite Booking Form submitted on Azurite website.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Alternate_Date_of_Surgery__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Date_of_Surgery__c</fullName>
    <label>Alternate Date of Surgery</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Companion_Date_of_Birth__c.field-meta.xml
<CustomField>
    <fullName>Companion_Date_of_Birth__c</fullName>
    <label>Companion Date of Birth</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Companion_Name__c.field-meta.xml
<CustomField>
    <fullName>Companion_Name__c</fullName>
    <label>Companion Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Current_bra_size__c.field-meta.xml
<CustomField>
    <fullName>Current_bra_size__c</fullName>
    <label>Current bra size</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Desired_bra_size__c.field-meta.xml
<CustomField>
    <fullName>Desired_bra_size__c</fullName>
    <label>Desired bra size</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Desired_Implants__c.field-meta.xml
<CustomField>
    <fullName>Desired_Implants__c</fullName>
    <label>Desired Implants?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Saline</fullName>
            </value>
            <value>
                <fullName>Silicone Gel</fullName>
            </value>
            <value>
                <fullName>Unsure</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Desired_Incision__c.field-meta.xml
<CustomField>
    <fullName>Desired_Incision__c</fullName>
    <label>Desired Incision?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Armpits</fullName>
            </value>
            <value>
                <fullName>Under Breast Crease</fullName>
            </value>
            <value>
                <fullName>Lower edge of Areola</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Desired_placement_of_implants__c.field-meta.xml
<CustomField>
    <fullName>Desired_placement_of_implants__c</fullName>
    <label>Desired placement of implants?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Behind of muscle</fullName>
            </value>
            <value>
                <fullName>In-front of muscle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Emergency_Contact_Name__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_Name__c</fullName>
    <description>This field is will save emergency contact name.</description>
    <label>Emergency Contact Name</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Emergency_Contact_Phone__c.field-meta.xml
<CustomField>
    <fullName>Emergency_Contact_Phone__c</fullName>
    <label>Emergency Contact Phone</label>
    <length>225</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Preferred_Date_of_Surgery__c.field-meta.xml
<CustomField>
    <fullName>Preferred_Date_of_Surgery__c</fullName>
    <label>Preferred Date of Surgery</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Procedure_Type__c.field-meta.xml
<CustomField>
    <fullName>Procedure_Type__c</fullName>
    <label>Procedure Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>General</fullName>
            </value>
            <value>
                <fullName>Dental Only</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Procedures_Requested_Please_Specify__c.field-meta.xml
<CustomField>
    <fullName>Procedures_Requested_Please_Specify__c</fullName>
    <label>Procedures Requested (Please Specify)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Superannuation__c.field-meta.xml
<CustomField>
    <fullName>Superannuation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>If you are seeking the compassionate release of superannuation funding, please attach your referral letter from your qualified GP. This letter is required before we supply our supporting documentation. Please note, if you choose to proceed with an alternative provider, or wish to cancel once approved for funding, you will incur a $500 service fee payable immediately.</description>
    <inlineHelpText>If you are seeking the compassionate release of superannuation funding, please attach your referral letter from your qualified GP. This letter is required before we supply our supporting documentation. Please note, if you choose to proceed with an alterna</inlineHelpText>
    <label>Superannuation</label>
    <referenceTo>Superannuation__c</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Current_bra_size__c.field-meta.xml
<CustomField>
    <fullName>Current_bra_size__c</fullName>
    <label>Current bra size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Desired_bra_size__c.field-meta.xml
<CustomField>
    <fullName>Desired_bra_size__c</fullName>
    <label>Desired bra size</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Desired_implants__c.field-meta.xml
<CustomField>
    <fullName>Desired_implants__c</fullName>
    <label>Desired implants</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Armpits</fullName>
            </value>
            <value>
                <fullName>Under Breast Crease</fullName>
            </value>
            <value>
                <fullName>Lower edge of Areola</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Desired_incision__c.field-meta.xml
<CustomField>
    <fullName>Desired_incision__c</fullName>
    <label>Desired incision</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Armpits</fullName>
            </value>
            <value>
                <fullName>Under Breast Crease</fullName>
            </value>
            <value>
                <fullName>Lower edge of Areola</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Desired_placement_of_implants__c.field-meta.xml
<CustomField>
    <fullName>Desired_placement_of_implants__c</fullName>
    <label>Desired placement of implants</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Behind muscle</fullName>
            </value>
            <value>
                <fullName>Front of muscle</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Procedures_Requested_Please_Specify__c.field-meta.xml
<CustomField>
    <fullName>Procedures_Requested_Please_Specify__c</fullName>
    <label>Procedures Requested (Please Specify)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Superannuation__c/Superannuation__c.object-meta.xml
<CustomObject>
    <label>Superannuation</label>
    <nameField>
        <label>Superannuation  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Superannuation Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestUtils.cls
@isTest
public class TestUtils {
    public static Booking__c createBooking(Boolean doInsert, Id contactId)
    {
        Booking__c NewBooking = new Booking__c();
        NewBooking.Name = 'Booking ';
        NewBooking.Contact__c = ContactId;
        
        //NewBooking.Superannuation__c = !String.isEmpty(CurrentLead.SuperannutionId__c) && CurrentLead.SuperannutionId__c != null ? CurrentLead.SuperannutionId__c : null;
        
        NewBooking.Preferred_Date_of_Surgery__c = Date.today()+(1);
        NewBooking.Alternate_Date_of_Surgery__c = Date.today()+(10);
        NewBooking.Emergency_Contact_Name__c = 'Fahad';
        NewBooking.Emergency_Contact_Phone__c = '123';
        NewBooking.Current_bra_size__c = 'not sure';
        NewBooking.Desired_bra_size__c = 'any';
        NewBooking.Desired_placement_of_implants__c = 'Behind of muscle';
        NewBooking.Desired_Implants__c = 'Saline';
        NewBooking.Desired_Incision__c = 'Armpits';
        
        NewBooking.Companion_Date_of_Birth__c = Date.today()+(-3000);
        NewBooking.Companion_Name__c = 'gusta';
        NewBooking.Procedure_Type__c = 'General';
        NewBooking.Procedures_Requested_Please_Specify__c = 'Any';
        
        if(doInsert)
            Insert NewBooking;
        return newBooking;
    }
    public static User createCommunityUser(Boolean doInsert)
    {
        Id p = [select id from profile where name='Azurite Customer Community User'].id;
        
        Account ac = new Account(name ='Grazitti') ;
        insert ac; 
        
        Contact con = new Contact(LastName ='testCon',AccountId = ac.Id);
        insert con;  
        
        User user = new User(alias = 'test123', email='test123@noemail.com',
                             emailencodingkey='UTF-8', lastname='Testing', languagelocalekey='en_US',
                             localesidkey='en_US', profileid = p, country='United States',IsActive =true,
                             ContactId = con.Id,
                             timezonesidkey='America/Los_Angeles', username='tester@noemail.com');
        if(doInsert)
            insert user;
        return user;
    }
}