force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Hotel.recordType-meta.xml
<RecordType>
    <fullName>Hotel</fullName>
    <active>true</active>
    <label>Hotel</label>
</RecordType>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Azurite Booking Form submitted on Azurite website.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings (Doctor)</relationshipLabel>
    <relationshipName>Doctor_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <summarizedField>Session__c.Session_days__c</summarizedField>
    <summaryForeignKey>Session__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/About__c.field-meta.xml
<CustomField>
    <fullName>About__c</fullName>
    <label>About</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Passport_Country__c.field-meta.xml
<CustomField>
    <fullName>Passport_Country__c</fullName>
    <label>Passport Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profile_Picture__c.field-meta.xml
<CustomField>
    <fullName>Profile_Picture__c</fullName>
    <inlineHelpText>Id of the document in Profile pictures folder</inlineHelpText>
    <label>Profile Picture</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <label>Doctor</label>
</RecordType>

force-app/main/default/objects/Itenrary__c/Itenrary__c.object-meta.xml
<CustomObject>
    <label>Itinerary</label>
    <nameField>
        <label>Itenrary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itineraries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Itenrary__c/fields/Airport_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Airport_Instructions__c</fullName>
    <label>Airport Instructions</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Itenrary__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Itineraries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Itenrary__c/fields/Customer_contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this lookup with connect this itenrary with client details.</description>
    <label>Customer Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Associated Contact must have Record type &quot;Customer&quot;</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Itineraries</relationshipLabel>
    <relationshipName>Itineraries1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Itenrary_Line_Item__c/Itenrary_Line_Item__c.object-meta.xml
<CustomObject>
    <description>this object is about the line items of Itenrary.</description>
    <label>Itinerary Line Item</label>
    <nameField>
        <label>Itenrary Line Items No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itinerary Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Itenrary_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Itenrary_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Itenrary_Line_Item__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Itenrary_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Itenrary_Line_Item__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Hotel</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Itenrary_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Itenrary_Line_Item__c/fields/Itenrary_Items__c.field-meta.xml
<CustomField>
    <fullName>Itenrary_Items__c</fullName>
    <label>Itenrary</label>
    <referenceTo>Itenrary__c</referenceTo>
    <relationshipName>Itenrary_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Itenrary_Line_Item__c/fields/Program_Itinerary_Details__c.field-meta.xml
<CustomField>
    <fullName>Program_Itinerary_Details__c</fullName>
    <label>Program Itinerary Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Itenrary_Line_Item__c/fields/Program_Itinerary_Info__c.field-meta.xml
<CustomField>
    <fullName>Program_Itinerary_Info__c</fullName>
    <description>This field is for the main information of program itinerary.</description>
    <inlineHelpText>Please provide info of Program Itinerary</inlineHelpText>
    <label>Program Itinerary Info</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <description>This object is for doctor session. This object will save record of Azurite start date and end date.</description>
    <label>Surgery Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surgery Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Surgery Sessions</relationshipLabel>
    <relationshipName>Surgery_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Date on which Azurite session is end.</inlineHelpText>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Medical_Balance__c.field-meta.xml
<CustomField>
    <fullName>Medical_Balance__c</fullName>
    <label>Medical Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Date on which azurite session is start.</inlineHelpText>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Taxi_Booking__c.field-meta.xml
<CustomField>
    <fullName>Taxi_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Taxi Booking</label>
    <referenceTo>Taxi_Booking__c</referenceTo>
    <relationshipLabel>Surgery Sessions</relationshipLabel>
    <relationshipName>Surgery_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Taxi_Booking__c/Taxi_Booking__c.object-meta.xml
<CustomObject>
    <label>Taxi Booking</label>
    <nameField>
        <label>Taxi Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taxi Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Taxi_Booking__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Taxi Bookings</relationshipLabel>
    <relationshipName>Taxi_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Taxi_Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Taxi Bookings</relationshipLabel>
    <relationshipName>Taxi_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Taxi_Booking__c/fields/Drop_off_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Drop_off_Date_Time__c</fullName>
    <label>Drop off Date / Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Taxi_Booking__c/fields/Pickup_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Date_Time__c</fullName>
    <label>Pickup Date / Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ItenraryCtrlTest.cls
@isTest
public class ItenraryCtrlTest {
    @isTest static void TestItenrary(){
        Test.startTest();
        	Account NewTestHotel = New Account();
        	NewTestHotel.Name = 'Testing Hotel';
        	NewTestHotel.Phone = '+923135290107';
        	NewTestHotel.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Hotel').getRecordTypeId();
        	Insert NewTestHotel;
        
        	Account NewTestAccount = New Account();
        	NewTestAccount.Name = 'Testing Account';
        	NewTestAccount.Phone = '+923135290107';
        	NewTestAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        	Insert NewTestAccount;
        
        	Account NewTestAccountDoc = New Account();
        	NewTestAccountDoc.Name = 'Testing Account Doc';
        	NewTestAccountDoc.Phone = '+923135290107';
        	NewTestAccountDoc.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Account').getRecordTypeId();
        	Insert NewTestAccountDoc;
        
            Contact NewTestContact = new Contact();
            NewTestContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
            NewTestContact.FirstName = 'Test';
            NewTestContact.LastName = 'Contact';
            NewTestContact.Passport_Country__c = 'Pakistan';
            NewTestContact.Gender__c = 'Male';
            NewTestContact.Birthdate = System.today();
            NewTestContact.Phone = '923135290107';
            NewTestContact.Email = 'fahad.munawar.khan@gmail.com';
            NewTestContact.About__c = 'This is testing about information';
            NewTestContact.Profile_Picture__c = '015O0000003CMEi';
        	NewTestContact.AccountId = NewTestAccount.Id;
            Insert NewTestContact;
        
        
        	Contact NewTestContactDoc = new Contact();
            NewTestContactDoc.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Doctor').getRecordTypeId();
            NewTestContactDoc.FirstName = 'Test Doctor';
            NewTestContactDoc.LastName = 'Contact 2';
            NewTestContactDoc.Passport_Country__c = 'Pakistan';
            NewTestContactDoc.Gender__c = 'Male';
            NewTestContactDoc.Birthdate = System.today();
            NewTestContactDoc.Phone = '923135290107';
            NewTestContactDoc.Email = 'testing2@gmail.com';
            NewTestContactDoc.About__c = 'This is testing about information';
            NewTestContactDoc.Profile_Picture__c = '015O0000003CMEi';
        	NewTestContactDoc.AccountId = NewTestAccountDoc.Id;
            Insert NewTestContactDoc;
        
        
        	Booking__c NewTestBooking = new Booking__c();
        	NewTestBooking.Name = 'New Booking__['+NewTestContact.FirstName+' '+NewTestContact.LastName+']';
        	NewTestBooking.Status__c = 'Open';
        	NewTestBooking.Contact__c = NewTestContact.Id;
        	Insert NewTestBooking;
        	
        	Taxi_Booking__c NewTestTaxi = new Taxi_Booking__c();
        	NewTestTaxi.Name = 'Test taxi';
        	NewTestTaxi.Pickup_Date_Time__c = system.today()+2;
        	NewTestTaxi.Drop_off_Date_Time__c = system.today()+4;
        	NewTestTaxi.Booking__c = NewTestBooking.Id;
        	NewTestTaxi.Contact__c = NewTestContact.Id;
        	Insert NewTestTaxi;
        
            Itenrary__c NewTestItenrary = new Itenrary__c();
            NewTestItenrary.Name = 'Testing Itenrary';
            //NewTestItenrary.CurrencyIsoCode = 'AUD';
            NewTestItenrary.Airport_Instructions__c = 'Testing aitport instructions';
            NewTestItenrary.Customer_contact__c = NewTestContact.Id;
        	NewTestItenrary.Booking__c = NewTestBooking.Id;
            Insert NewTestItenrary;
        	
        	Datetime myDateTime = Datetime.newInstance(2019, 2, 17);
        	List<Itenrary_Line_Item__c> LineItems = new list<Itenrary_Line_Item__c>();
            for(Integer i = 0; i < 5; i++){
                Itenrary_Line_Item__c NewLineItems = new Itenrary_Line_Item__c();
                NewLineItems.Name = String.valueOf(i);
                NewLineItems.Contact__c = NewTestContact.Id;
                if(i == 2){
                	NewLineItems.Hotel__c = NewTestHotel.Id;
                }
                NewLineItems.Itenrary_Items__c = NewTestItenrary.Id;
                NewLineItems.Program_Itinerary_Info__c = '<b>Testing Info</b> for the test class';
                NewLineItems.Program_Itinerary_Details__c = '1055 Ekachai Road, Bangbon, Bangbon, Bangkok 10150';
                NewLineItems.Start_Date__c = myDateTime;
                Datetime newDateTime = myDateTime.addDays(i);
                NewLineItems.End_Date__c = newDateTime;
                NewLineItems.Booking__c = NewTestBooking.Id;
                LineItems.add(NewLineItems);
            }
        
        	List<Session__c> SessionList = new List<Session__c>();
            for(Integer i=0 ; i<5 ; i++){
                Session__c NewTestSess = new Session__c();
                NewTestSess.Start_Date__c = system.today()+i;
                NewTestSess.End_Date__c = system.today()+i+1;
                NewTestSess.Doctor__c = NewTestContactDoc.Id;
                NewTestSess.Medical_Balance__c = 120 + i;
                NewTestSess.Booking__c = NewTestBooking.Id;
                SessionList.add(NewTestSess);
            }
        	Insert SessionList;
        
        
            if(LineItems.size() > 0){
                Insert LineItems;
            }
        	
        	PageReference pageRf = Page.ItineraryPDF;
        	Test.setCurrentPage(pageRf);
        	pageRf.getParameters().put('id', NewTestItenrary.Id);
        	
        	ApexPages.StandardController scc = new ApexPages.StandardController(NewTestItenrary);
        	ItenraryCtrl CtrlTest = new ItenraryCtrl(scc);
        	
        Test.stopTest();
    }
}