force-app/main/default/objects/Account/fields/Airport_Details__c.field-meta.xml
<CustomField>
    <fullName>Airport_Details__c</fullName>
    <label>Airport Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Azurite Booking Form submitted on Azurite website.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings (Doctor)</relationshipLabel>
    <relationshipName>Doctor_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Personal_Assistant__c.field-meta.xml
<CustomField>
    <fullName>Personal_Assistant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Personal Assistant</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Personal Assistant</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings (Personal Assistant)</relationshipLabel>
    <relationshipName>Bookings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Procedures_Requested_Please_Specify__c.field-meta.xml
<CustomField>
    <fullName>Procedures_Requested_Please_Specify__c</fullName>
    <label>Procedures Requested (Please Specify)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <summarizedField>Session__c.Session_days__c</summarizedField>
    <summaryForeignKey>Session__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Total_Medical_Balance__c.field-meta.xml
<CustomField>
    <fullName>Total_Medical_Balance__c</fullName>
    <label>Total Medical Balance</label>
    <summarizedField>Session__c.Medical_Balance__c</summarizedField>
    <summaryForeignKey>Session__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Hospital_Balance__c.field-meta.xml
<CustomField>
    <fullName>Hospital_Balance__c</fullName>
    <label>Hospital Balance</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Procedures_Requested_Please_Specify__c.field-meta.xml
<CustomField>
    <fullName>Procedures_Requested_Please_Specify__c</fullName>
    <label>Procedures Requested (Please Specify)</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profile_Picture__c.field-meta.xml
<CustomField>
    <fullName>Profile_Picture__c</fullName>
    <inlineHelpText>Id of the document in Profile pictures folder</inlineHelpText>
    <label>Profile Picture</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Itenrary__c/Itenrary__c.object-meta.xml
<CustomObject>
    <label>Itinerary</label>
    <nameField>
        <label>Itenrary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itineraries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Itenrary__c/fields/Airport__c.field-meta.xml
<CustomField>
    <fullName>Airport__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Airport</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Airport</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Itineraries</relationshipLabel>
    <relationshipName>Itineraries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Itenrary__c/fields/Airport_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Airport_Instructions__c</fullName>
    <label>Airport Instructions</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Itenrary__c/fields/Azurite_Arrive__c.field-meta.xml
<CustomField>
    <fullName>Azurite_Arrive__c</fullName>
    <formula>Booking__r.Arrival_Date_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Azurite Arrive</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Itenrary__c/fields/Azurite_Depart__c.field-meta.xml
<CustomField>
    <fullName>Azurite_Depart__c</fullName>
    <formula>Booking__r.Departure_Date_Time__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Azurite Depart</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Itenrary__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Itineraries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Itenrary__c/fields/Customer_contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this lookup with connect this itenrary with client details.</description>
    <label>Customer Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Associated Contact must have Record type &quot;Customer&quot;</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Itineraries</relationshipLabel>
    <relationshipName>Itineraries1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Itenrary_Line_Item__c/Itenrary_Line_Item__c.object-meta.xml
<CustomObject>
    <description>this object is about the line items of Itenrary.</description>
    <label>Itinerary Line Item</label>
    <nameField>
        <label>Itenrary Line Items No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itinerary Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Itenrary_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Itenrary_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Itenrary_Line_Item__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Itenrary_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Itenrary_Line_Item__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Hotel</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Itenrary_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Itenrary_Line_Item__c/fields/Itenrary_Items__c.field-meta.xml
<CustomField>
    <fullName>Itenrary_Items__c</fullName>
    <label>Itenrary</label>
    <referenceTo>Itenrary__c</referenceTo>
    <relationshipName>Itenrary_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Itenrary_Line_Item__c/fields/Program_Itinerary_Details__c.field-meta.xml
<CustomField>
    <fullName>Program_Itinerary_Details__c</fullName>
    <label>Program Itinerary Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Itenrary_Line_Item__c/fields/Program_Itinerary_Info__c.field-meta.xml
<CustomField>
    <fullName>Program_Itinerary_Info__c</fullName>
    <description>This field is for the main information of program itinerary.</description>
    <inlineHelpText>Please provide info of Program Itinerary</inlineHelpText>
    <label>Program Itinerary Info</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <description>This object is for doctor session. This object will save record of Azurite start date and end date.</description>
    <label>Surgery Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surgery Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Surgery Sessions</relationshipLabel>
    <relationshipName>Surgery_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Date on which Azurite session is end.</inlineHelpText>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Medical_Balance__c.field-meta.xml
<CustomField>
    <fullName>Medical_Balance__c</fullName>
    <label>Medical Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Procedures__c.field-meta.xml
<CustomField>
    <fullName>Procedures__c</fullName>
    <label>Procedures</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Date on which azurite session is start.</inlineHelpText>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/ItenraryCtrl.cls
public class ItenraryCtrl {
	
    private string itenraryId {set;get;}
    public Itenrary__c ItenraryObj {set;get;}
    public Contact ConObj {set;get;}
    public Contact PersonalAssObj {set;get;}
    public Account AirportInfo {set;get;}
    public string detectuser {set;get;}
    public double timezone {set;get;}
    public Datetime az_arrive {set;get;}
    public Datetime az_depart {set;get;}
    public List<Session__c> SessInfo {set;get;}
    public String SessProcedure {set;get;}
    public String SessSurgonNames {set;get;}
    public Datetime SessStartDateRange {set;get;}
    public Datetime SessEndDateRange {set;get;}
    public Integer ItiSize {set;get;}
    public Map<String, Decimal> CurrencyRates {set; get;}
    Public String MedIsoCode {set; get;}
    Public Decimal TotalAmount = 0;
    Public Decimal TotalMedBalance {set; get;}
    public DateTime arrival{get;set;}
    public DateTime depart{get;set;}
    
    public ItenraryCtrl(Apexpages.StandardController sc){
        itenraryId = ApexPages.currentPage().getParameters().get('Id');
        ItenraryObj = [SELECT id, Airport__c, Booking__r.Procedures_Requested_Please_Specify__c, Customer_contact__c, Airport_Instructions__c,
                       Azurite_Arrive__c, Azurite_Depart__c, Booking__r.Personal_Assistant__c, Booking__r.Total_Medical_Balance__c, Booking__r.Doctor__r.FirstName, CurrencyIsoCode,
                       (SELECT id, Name, Program_Itinerary_Info__c, Program_Itinerary_Details__c, Start_Date__c, End_Date__c FROM Itenrary_Line_Items__r ORDER BY Start_Date__c, name ASC),
                       Booking__r.Id
                       FROM Itenrary__c WHERE Id =: itenraryId];
        
        

        ItiSize = ItenraryObj.Itenrary_Line_Items__r.size();
        GetContactInfo(ItenraryObj.Customer_contact__c);
        GetPersonalAssistant(ItenraryObj.Booking__r.Personal_Assistant__c);
        GetAirportInstructions(ItenraryObj.Airport__c);
        GetSessionInfo(ItenraryObj.Booking__r.Id);
        UpdateLineItemsDateTime();
        TotalMedBalance = TotalMedBalance(ItenraryObj.Booking__r.Id);
        
        Profile pfile = [Select Name from Profile where Id =: userinfo.getProfileid()];
        String pname = pfile.name;
        detectuser = pfile.name;
        
        //System.debug(ItenraryObj.Azurite_Depart__c + '|' + ItenraryObj.Azurite_Arrive__c);
        arrival = ItenraryObj.Azurite_Arrive__c + GetOffset(ItenraryObj.Azurite_Arrive__c);
        depart = ItenraryObj.Azurite_Depart__c + GetOffset(ItenraryObj.Azurite_Depart__c);
    }
    
    
    public Double GetOffset(Datetime DateTimeValue){
        TimeZone tz = UserInfo.getTimeZone();
        //Milliseconds to Day
        timezone = tz.getOffset(DateTimeValue) / (1000 * 3600 * 24.0);
        return timezone;
    }
    
    public List<Itenrary_Line_Item__c> UpdateLineItemsDateTime(){
        for(Itenrary_Line_Item__c LineItemInfo : ItenraryObj.Itenrary_Line_Items__r){
            LineItemInfo.Start_Date__c = LineItemInfo.Start_Date__c + getOffset(LineItemInfo.Start_Date__c);
            LineItemInfo.End_Date__c = LineItemInfo.End_Date__c + getOffset(LineItemInfo.End_Date__c);
        }
      
        return ItenraryObj.Itenrary_Line_Items__r;
    }
    
    
    public List<Session__c> GetSessionInfo(String BookingId){
        SessInfo = new List<Session__c>();
        SessSurgonNames = '';
        if(! String.isEmpty(BookingId)){
			SessInfo = [SELECT Id, Name, 
                        		Booking__r.Id, 
                        		CreatedDate,
                        		Procedures__c,
                        		Medical_Balance__c,
                        		Doctor__r.FirstName,
                        		Doctor__r.LastName,
                        		Start_Date__c,
                        		End_Date__c
                        FROM Session__c WHERE Booking__r.Id =: BookingId order by createdDate ASC];
            if(SessInfo.size() > 0){
                SessProcedure = SessInfo[0].Procedures__c;
                Set<String> SurgonNames = new Set<String>();
                for(Session__c sessdet : SessInfo){
                    String Name = sessdet.Doctor__r.FirstName + ' ' + sessdet.Doctor__r.LastName;
                    SurgonNames.add(Name);
                }
                SessSurgonNames = String.join((Iterable<String>)SurgonNames, ',');
                
                
                SessStartDateRange = SessInfo[SessInfo.size()-1].Start_Date__c;
                SessEndDateRange = SessInfo[0].End_Date__c;
                system.debug('Start:' + SessStartDateRange + 'End: '+ SessEndDateRange);
            }
        }
        return SessInfo;
    }
    public Contact GetContactInfo(String ContactId){
        ConObj = new Contact();
        if(! String.isempty(ContactId) )
        {
            ConObj = [SELECT FirstName, LastName, Email, Phone, Hospital_Balance__c, Profile_Picture__c FROM Contact WHERE Id =:ContactId];
        }
        return ConObj;
    }
    public Contact GetPersonalAssistant(String ContactId){
        PersonalAssObj = new Contact();
        if(! String.isempty(ContactId) )
        {
            PersonalAssObj = [SELECT FirstName, LastName, Email, Phone, Profile_Picture__c FROM Contact WHERE Id =:ContactId];
        }
        return PersonalAssObj;
    }
    public Account GetAirportInstructions(String AccountId){
        AirportInfo = new Account();
        if(!String.isEmpty(AccountId)){
            AirportInfo = [SELECT Name, Airport_Details__c FROM Account Where Id =: AccountId];
        }
        return AirportInfo;
    }
    public Decimal TotalMedBalance(String BookingId){
        
        List<Session__c> SessionListCheck = new List<Session__c>();
        SessionListCheck = [SELECT Id FROM Session__c Where Booking__c =: BookingId];
        
        if(SessionListCheck.size() > 0){
        	MedIsoCode = [SELECT CurrencyIsoCode FROM Session__c Where Booking__c =: BookingId Order By Createddate ASC Limit 1].CurrencyIsoCode;
        } else{ 
        	MedIsoCode = UserInfo.getDefaultCurrency();
        }
        system.debug(MedIsoCode);
        system.debug([SELECT Medical_Balance__c FROM Session__c Where Booking__c =: BookingId AND CurrencyISOCode =: MedIsoCode]);
        For(Session__c SessMedBal : [SELECT Medical_Balance__c FROM Session__c Where Booking__c =: BookingId AND CurrencyISOCode =: MedIsoCode]){
            TotalAmount = TotalAmount + SessMedBal.Medical_Balance__c;
        }
        System.debug(MedIsoCode+' '+TotalAmount);
        
        return TotalAmount;
        
    }
    
}