force-app/main/default/objects/Account/fields/Hotel_Address__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Address__c</fullName>
    <label>Hotel Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/Account.recordType-meta.xml
<RecordType>
    <fullName>Account</fullName>
    <active>true</active>
    <label>Account</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/Hotel.recordType-meta.xml
<RecordType>
    <fullName>Hotel</fullName>
    <active>true</active>
    <label>Hotel</label>
</RecordType>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Azurite Booking Form submitted on Azurite website.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings (Doctor)</relationshipLabel>
    <relationshipName>Doctor_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <summarizedField>Session__c.Session_days__c</summarizedField>
    <summaryForeignKey>Session__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/About__c.field-meta.xml
<CustomField>
    <fullName>About__c</fullName>
    <label>About</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Passport_Country__c.field-meta.xml
<CustomField>
    <fullName>Passport_Country__c</fullName>
    <label>Passport Country</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profile_Picture__c.field-meta.xml
<CustomField>
    <fullName>Profile_Picture__c</fullName>
    <inlineHelpText>Id of the document in Profile pictures folder</inlineHelpText>
    <label>Profile Picture</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Doctor.recordType-meta.xml
<RecordType>
    <fullName>Doctor</fullName>
    <active>true</active>
    <label>Doctor</label>
</RecordType>

force-app/main/default/objects/Hotel_Reservation__c/Hotel_Reservation__c.object-meta.xml
<CustomObject>
    <label>Hotel Reservation</label>
    <nameField>
        <label>Hotel Reservation #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotel Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel_Reservation__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Hotel Reservations</relationshipLabel>
    <relationshipName>Hotel_Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Hotel_Reservation__c/fields/check_in__c.field-meta.xml
<CustomField>
    <fullName>check_in__c</fullName>
    <label>check in</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Hotel_Reservation__c/fields/Check_out__c.field-meta.xml
<CustomField>
    <fullName>Check_out__c</fullName>
    <label>Check out</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Hotel_Reservation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Hotel Reservations</relationshipLabel>
    <relationshipName>Hotel_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hotel_Reservation__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Hotel</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hotel Reservations</relationshipLabel>
    <relationshipName>Hotel_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hotel_Reservation__c/fields/Hotel_Details__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Details__c</fullName>
    <inlineHelpText>For itinerary items details.</inlineHelpText>
    <label>Hotel Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Itenrary__c/Itenrary__c.object-meta.xml
<CustomObject>
    <label>Itinerary</label>
    <nameField>
        <label>Itenrary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itineraries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Itenrary__c/fields/Airport_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Airport_Instructions__c</fullName>
    <label>Airport Instructions</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Itenrary__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Itineraries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Itenrary__c/fields/Customer_contact__c.field-meta.xml
<CustomField>
    <fullName>Customer_contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>this lookup with connect this itenrary with client details.</description>
    <label>Customer Contact</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Associated Contact must have Record type &quot;Customer&quot;</errorMessage>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Itineraries</relationshipLabel>
    <relationshipName>Itineraries1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <description>This object is for doctor session. This object will save record of Azurite start date and end date.</description>
    <label>Surgery Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surgery Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Surgery Sessions</relationshipLabel>
    <relationshipName>Surgery_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Date on which Azurite session is end.</inlineHelpText>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Date on which azurite session is start.</inlineHelpText>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Taxi_Booking__c.field-meta.xml
<CustomField>
    <fullName>Taxi_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Taxi Booking</label>
    <referenceTo>Taxi_Booking__c</referenceTo>
    <relationshipLabel>Surgery Sessions</relationshipLabel>
    <relationshipName>Surgery_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Taxi_Booking__c/Taxi_Booking__c.object-meta.xml
<CustomObject>
    <label>Taxi Booking</label>
    <nameField>
        <label>Taxi Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taxi Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Taxi_Booking__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Taxi Bookings</relationshipLabel>
    <relationshipName>Taxi_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Taxi_Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Taxi Bookings</relationshipLabel>
    <relationshipName>Taxi_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Taxi_Booking__c/fields/Drop_off_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Drop_off_Date_Time__c</fullName>
    <label>Drop off Date / Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Taxi_Booking__c/fields/Pickup_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Date_Time__c</fullName>
    <label>Pickup Date / Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Taxi_Booking__c/fields/Pickup_Drop_Location__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Drop_Location__c</fullName>
    <label>Pickup / Drop Location</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Taxi_Booking__c/fields/Route_Details__c.field-meta.xml
<CustomField>
    <fullName>Route_Details__c</fullName>
    <label>Route Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/CopyReservationsTriggerHandlerTest.cls
@isTest
public class CopyReservationsTriggerHandlerTest {
    @isTest static void CopyReservationsItenaryTesting(){
        Test.startTest();
        
        	
        
                Contact NewTestContact = new Contact();
                NewTestContact.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Customer').getRecordTypeId();
                NewTestContact.FirstName = 'Test';
                NewTestContact.LastName = 'Contact';
                NewTestContact.Passport_Country__c = 'Pakistan';
                NewTestContact.Gender__c = 'Male';
                NewTestContact.Birthdate = System.today();
                NewTestContact.Phone = '923135290107';
                NewTestContact.Email = 'fahad.munawar.khan@gmail.com';
                NewTestContact.About__c = 'This is testing about information';
                NewTestContact.Profile_Picture__c = '015O0000003CMEi';
                NewTestContact.AccountId = GenerateAcc('Account');
                Insert NewTestContact;
        		
        		
        		Contact NewTestDoc = new Contact();
                NewTestDoc.RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Doctor').getRecordTypeId();
                NewTestDoc.FirstName = 'Test 2';
                NewTestDoc.LastName = 'Contact';
                NewTestDoc.Passport_Country__c = 'Pakistan';
                NewTestDoc.Gender__c = 'Male';
                NewTestDoc.Birthdate = System.today();
                NewTestDoc.Phone = '923135290107';
                NewTestDoc.Email = 'Testing123@gmail.com';
                NewTestDoc.About__c = 'This is testing about information';
                NewTestDoc.Profile_Picture__c = '015O0000003CMEi';
                NewTestDoc.AccountId = GenerateAcc('Account');
                Insert NewTestDoc;
        		
        
                Booking__c NewTestBooking = new Booking__c();
                NewTestBooking.Name = 'New Booking__['+NewTestContact.FirstName+' '+NewTestContact.LastName+']';
                NewTestBooking.Status__c = 'Open';
                NewTestBooking.Contact__c = NewTestContact.Id;
                Insert NewTestBooking;
        
        			Hotel_Reservation__c NewRes = new Hotel_Reservation__c();
        			NewRes.Name = 'Hotel_[Testing Reservation]';
        			NewRes.Contact__c = NewTestContact.Id;
        			NewRes.Hotel__c = GenerateAcc('Hotel');
        			NewRes.Hotel_Details__c = 'Reservation no. 2599120 Daily Buffet Breakfast 2 persons One Bedroom Suite Unlimited Wifi CHATRIUM RESIDENCE SATHON BANGKOK 291 Soi Naradhiwas Rajanagarindra 24, New Sathon Road, Bangkok 10120, Thailand Tel: +66 (0) 2672 0200 Fax: +66 (0) 2672 0190 Email: info.crst@chatrium.com';
        			NewRes.Booking__c = NewTestBooking.Id;
                        Datetime Checkin = Datetime.newInstance(2020, 2, 17);
                        Datetime Checkout = Checkin.addDays(2);
        			NewRes.check_in__c = Checkin;
        			NewRes.Check_out__c = Checkout;
        			Insert NewRes;
        			
        				List<Taxi_Booking__c> TaxiBookingsToCreate = new List<Taxi_Booking__c>();
                        for(Integer i=0; i<4; i++){
                            Taxi_Booking__c Newtesttaxi = new Taxi_Booking__c();
                            Newtesttaxi.Name = 'New Taxi Booking_['+i+']';
                            Newtesttaxi.Contact__c = NewTestContact.Id;
                            Newtesttaxi.Booking__c = NewTestBooking.Id;
                            	Datetime pickup = Datetime.newInstance(2020, 2, 17);
                            Newtesttaxi.Pickup_Date_Time__c = pickup;
                            	Datetime Dropoff = pickup.addDays(i);
                            Newtesttaxi.Drop_off_Date_Time__c = Dropoff;
                            Newtesttaxi.Pickup_Drop_Location__c = 'Testing location for test';
                            Newtesttaxi.Route_Details__c = 'Testing Route Details for test';
                            TaxiBookingsToCreate.add(Newtesttaxi);
                        }
        
        				List<Session__c> ListSess = new List<Session__c>();
        				for(Integer i=0; i<4; i++){
                            Session__c SurgerySess = new Session__c();
                            SurgerySess.Start_Date__c = System.today();
                            SurgerySess.End_Date__c = System.today() + i;
                            
                            SurgerySess.Booking__c = NewTestBooking.Id;
                            SurgerySess.Doctor__c = NewTestDoc.Id;
                            ListSess.add(SurgerySess);
                        }
        				Insert ListSess;
        
                        if(TaxiBookingsToCreate.size() > 0){
                            Insert TaxiBookingsToCreate;
                        }
        
                        Itenrary__c NewTestItenrary = new Itenrary__c();
                        NewTestItenrary.Name = 'Testing Itenrary';
                        //NewTestItenrary.CurrencyIsoCode = 'AUD';
                        NewTestItenrary.Airport_Instructions__c = 'Testing aitport instructions';
                        NewTestItenrary.Customer_contact__c = NewTestContact.Id;
                        NewTestItenrary.Booking__c = NewTestBooking.Id;
                        Insert NewTestItenrary;
        Test.stopTest();
    }
    
    Private static Id GenerateAcc(String Acctype){
        Account NewTestAccount = New Account();
        NewTestAccount.Name = 'Testing Account';
        NewTestAccount.Phone = '+923135290107';
        NewTestAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get(Acctype).getRecordTypeId();
        if(Acctype == 'Hotel'){
            NewTestAccount.Hotel_Address__c = '401 7th Ave, New York, NY 10001, United States';
        }
        Insert NewTestAccount;
        return NewTestAccount.Id;
    }
}