force-app/main/default/objects/Account/fields/Hotel_Address__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Address__c</fullName>
    <label>Hotel Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Booking__c/Booking__c.object-meta.xml
<CustomObject>
    <description>Azurite Booking Form submitted on Azurite website.</description>
    <label>Booking</label>
    <nameField>
        <label>Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bookings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Surgeon</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Doctor</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Bookings (Doctor)</relationshipLabel>
    <relationshipName>Doctor_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <label>End Date 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Hospital__c.field-meta.xml
<CustomField>
    <fullName>Hospital__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field will display that user booked which hospital.</description>
    <inlineHelpText>Please select hospital.</inlineHelpText>
    <label>Hospital</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Hospital</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Bookings</relationshipLabel>
    <relationshipName>Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Session__c.field-meta.xml
<CustomField>
    <fullName>Session__c</fullName>
    <label>Session</label>
    <summarizedField>Session__c.Session_days__c</summarizedField>
    <summaryForeignKey>Session__c.Booking__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/Booking__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <label>Start Date 1</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Hotel_Reservation__c/Hotel_Reservation__c.object-meta.xml
<CustomObject>
    <label>Hotel Reservation</label>
    <nameField>
        <label>Hotel Reservation #</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Hotel Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Hotel_Reservation__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Hotel Reservations</relationshipLabel>
    <relationshipName>Hotel_Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Hotel_Reservation__c/fields/check_in__c.field-meta.xml
<CustomField>
    <fullName>check_in__c</fullName>
    <label>check in</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Hotel_Reservation__c/fields/Check_out__c.field-meta.xml
<CustomField>
    <fullName>Check_out__c</fullName>
    <label>Check out</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Hotel_Reservation__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Hotel Reservations</relationshipLabel>
    <relationshipName>Hotel_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hotel_Reservation__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Hotel</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Hotel Reservations</relationshipLabel>
    <relationshipName>Hotel_Reservations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hotel_Reservation__c/fields/Hotel_Details__c.field-meta.xml
<CustomField>
    <fullName>Hotel_Details__c</fullName>
    <inlineHelpText>For itinerary items details.</inlineHelpText>
    <label>Hotel Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Itenrary__c/Itenrary__c.object-meta.xml
<CustomObject>
    <label>Itinerary</label>
    <nameField>
        <label>Itenrary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itineraries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Itenrary__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Itineraries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Itenrary_Line_Item__c/Itenrary_Line_Item__c.object-meta.xml
<CustomObject>
    <description>this object is about the line items of Itenrary.</description>
    <label>Itinerary Line Item</label>
    <nameField>
        <label>Itenrary Line Items No</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itinerary Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Itenrary_Line_Item__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Itenrary_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Itenrary_Line_Item__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Itenrary_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Itenrary_Line_Item__c/fields/Hotel__c.field-meta.xml
<CustomField>
    <fullName>Hotel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hotel</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Hotel</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipName>Itenrary_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Itenrary_Line_Item__c/fields/Itenrary_Items__c.field-meta.xml
<CustomField>
    <fullName>Itenrary_Items__c</fullName>
    <label>Itenrary</label>
    <referenceTo>Itenrary__c</referenceTo>
    <relationshipName>Itenrary_Line_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Itenrary_Line_Item__c/fields/Program_Itinerary_Details__c.field-meta.xml
<CustomField>
    <fullName>Program_Itinerary_Details__c</fullName>
    <label>Program Itinerary Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Itenrary_Line_Item__c/fields/Program_Itinerary_Info__c.field-meta.xml
<CustomField>
    <fullName>Program_Itinerary_Info__c</fullName>
    <description>This field is for the main information of program itinerary.</description>
    <inlineHelpText>Please provide info of Program Itinerary</inlineHelpText>
    <label>Program Itinerary Info</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Session__c/Session__c.object-meta.xml
<CustomObject>
    <description>This object is for doctor session. This object will save record of Azurite start date and end date.</description>
    <label>Surgery Session</label>
    <nameField>
        <label>Session Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Surgery Sessions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Session__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipName>Sessions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Doctor__c.field-meta.xml
<CustomField>
    <fullName>Doctor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Doctor</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Surgery Sessions</relationshipLabel>
    <relationshipName>Surgery_Sessions</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <inlineHelpText>Date on which Azurite session is end.</inlineHelpText>
    <label>End Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Hospital__c.field-meta.xml
<CustomField>
    <fullName>Hospital__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Hospital</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Surgery Sessions</relationshipLabel>
    <relationshipName>Surgery_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Medical_Balance__c.field-meta.xml
<CustomField>
    <fullName>Medical_Balance__c</fullName>
    <label>Medical Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Procedures__c.field-meta.xml
<CustomField>
    <fullName>Procedures__c</fullName>
    <label>Procedures</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <inlineHelpText>Date on which azurite session is start.</inlineHelpText>
    <label>Start Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Session__c/fields/Taxi_Booking__c.field-meta.xml
<CustomField>
    <fullName>Taxi_Booking__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Taxi Booking</label>
    <referenceTo>Taxi_Booking__c</referenceTo>
    <relationshipLabel>Surgery Sessions</relationshipLabel>
    <relationshipName>Surgery_Sessions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Taxi_Booking__c/Taxi_Booking__c.object-meta.xml
<CustomObject>
    <label>Taxi Booking</label>
    <nameField>
        <label>Taxi Booking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Taxi Bookings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Taxi_Booking__c/fields/Booking__c.field-meta.xml
<CustomField>
    <fullName>Booking__c</fullName>
    <label>Booking</label>
    <referenceTo>Booking__c</referenceTo>
    <relationshipLabel>Taxi Bookings</relationshipLabel>
    <relationshipName>Taxi_Bookings</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Taxi_Booking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.RecordTypeId</field>
            <operation>equals</operation>
            <value>Customer</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Taxi Bookings</relationshipLabel>
    <relationshipName>Taxi_Bookings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Taxi_Booking__c/fields/Drop_off_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Drop_off_Date_Time__c</fullName>
    <label>Drop off Date / Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Taxi_Booking__c/fields/Pickup_Date_Time__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Date_Time__c</fullName>
    <label>Pickup Date / Time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Taxi_Booking__c/fields/Pickup_Drop_Location__c.field-meta.xml
<CustomField>
    <fullName>Pickup_Drop_Location__c</fullName>
    <label>Pickup / Drop Location</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Taxi_Booking__c/fields/Route_Details__c.field-meta.xml
<CustomField>
    <fullName>Route_Details__c</fullName>
    <label>Route Details</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/classes/CopyReservationsTriggerHandler.cls
/**
 * @File Name          : CopyReservationsTriggerHandler.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 27/11/2019, 1:57:53 pm
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    27/11/2019   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public class CopyReservationsTriggerHandler {
	
    public static void CopyReservationsItenary(List<Itenrary__c> NewItenrary){
		Map<id, id> BookToIts = new Map<id, id>();
        Map<Id, List<Hotel_Reservation__c>> BookToHotelreservation = new Map<Id, List<Hotel_Reservation__c>>();
        Map<Id, List<Taxi_Booking__c>> BookToTaxiBooking = new Map<Id, List<Taxi_Booking__c>>();
        Map<Id, List<Session__c>> BookingToSessions = new Map<Id, List<Session__c>>();
        List<Itenrary_Line_Item__c> LineItemsToCreate = new List<Itenrary_Line_Item__c>();
        List<Itenrary_Line_Item__c> LineItemsToUpdate = new List<Itenrary_Line_Item__c>();

        String test;
        String ItenraryId;
        String Hotel_Address = '';
        
        
        List<id> Bookings = new List<id>();
        for(Itenrary__c its : NewItenrary){
            BookToIts.put(its.Booking__c, its.Id);
            Bookings.add(its.Booking__c);
        }
        
        for(Booking__c book : [SELECT id, 
                               	(SELECT id, Name, Contact__c, Hotel__r.Name, Hotel__r.Hotel_Address__c, Hotel_Details__c, CurrencyIsoCode, Booking__c, check_in__c, Check_out__c FROM Hotel_Reservations__r),
                               	(SELECT id, Name, Contact__c, CurrencyIsoCode, Booking__c, Pickup_Date_Time__c, Drop_off_Date_Time__c, Pickup_Drop_Location__c, Route_Details__c  FROM Taxi_Bookings__r),
                               	(SELECT Id, Name, Booking__c, Start_Date__c, End_Date__c, CurrencyIsoCode, Medical_Balance__c, Doctor__c, Doctor__r.FirstName, Doctor__r.LastName, Hospital__r.BillingCountry, Hospital__r.BillingCity, Hospital__r.BillingStreet, Procedures__c FROM Sessions__r)
                               FROM Booking__c WHERE Id IN : Bookings]){
            if( BookToIts.ContainsKey(book.Id) ){
            	BookToHotelreservation.put(book.Id, book.Hotel_Reservations__r);
                BookToTaxiBooking.put(book.Id, book.Taxi_Bookings__r);
                BookingToSessions.put(book.Id, book.Sessions__r);
        	}
        }
        //try{
            for(Itenrary__c ComingIts : NewItenrary){
                //test = BookToIts.get(ComingIts.Booking__c);
                if(BookToHotelreservation.get(ComingIts.Booking__c).size() > 0){
                    for(Hotel_Reservation__c resForIts : BookToHotelreservation.get(ComingIts.Booking__c)){
                        Itenrary_Line_Item__c LineItems = new Itenrary_Line_Item__c();
                        LineItems.Name = resForIts.Name;
                        LineItems.Contact__c = resForIts.Contact__c;
                        LineItems.Hotel__c = resForIts.Hotel__c;
                        LineItems.CurrencyIsoCode = resForIts.CurrencyIsoCode;
                        LineItems.Booking__c = resForIts.Booking__c; 
                        LineItems.Start_Date__c = resForIts.check_in__c;
                        LineItems.End_Date__c = resForIts.Check_out__c;
                        if(!String.isEmpty(resForIts.Hotel__r.Hotel_Address__c)){
                            Hotel_Address =  ' - ['+resForIts.Hotel__r.Hotel_Address__c+']';
                        }
                        LineItems.Program_Itinerary_Info__c = '<b>'+resForIts.Hotel__r.Name+'</b>'+Hotel_Address;
                        LineItems.Program_Itinerary_Details__c = resForIts.Hotel_Details__c;
                        LineItems.Itenrary_Items__c = BookToIts.get(ComingIts.Booking__c);
                        LineItemsToCreate.add(LineItems);
                    }
                }
                if(BookToTaxiBooking.get(ComingIts.Booking__c).size() > 0){
                    for(Taxi_Booking__c TaxiToBooks : BookToTaxiBooking.get(ComingIts.Booking__c)){
                        Itenrary_Line_Item__c LineItems = new Itenrary_Line_Item__c();
                        LineItems.Name = TaxiToBooks.Name;
                        LineItems.Contact__c = TaxiToBooks.Contact__c;
                        LineItems.CurrencyIsoCode = TaxiToBooks.CurrencyIsoCode;
                        LineItems.Booking__c = TaxiToBooks.Booking__c;
                        LineItems.Start_Date__c = TaxiToBooks.Pickup_Date_Time__c;
                        LineItems.End_Date__c = TaxiToBooks.Drop_off_Date_Time__c;
                        LineItems.Program_Itinerary_Info__c = TaxiToBooks.Pickup_Drop_Location__c;
                        LineItems.Program_Itinerary_Details__c = TaxiToBooks.Route_Details__c;
                        LineItems.Itenrary_Items__c = BookToIts.get(ComingIts.Booking__c);
                        LineItemsToCreate.add(LineItems);
                    }
                }
                if(BookingToSessions.get(ComingIts.Booking__c).size() > 0){
                    for(Session__c SessionToBooks : BookingToSessions.get(ComingIts.Booking__c)){
                        String BillingStreet = '';
                        String BillingCity = '';
                        String BillingCountry = '';
                        String Procedures = '';
                        Decimal Balance;
                        Itenrary_Line_Item__c LineItems = new Itenrary_Line_Item__c();
                        LineItems.Name = SessionToBooks.Name;
                        LineItems.Contact__c = SessionToBooks.Doctor__c;
                        LineItems.CurrencyIsoCode = SessionToBooks.CurrencyIsoCode;
                        LineItems.Booking__c = SessionToBooks.Booking__c;
                        LineItems.Start_Date__c = SessionToBooks.Start_Date__c;
                        LineItems.End_Date__c = SessionToBooks.End_Date__c;
                        
                        if(!String.isEmpty(SessionToBooks.Hospital__r.BillingStreet)){
                            BillingStreet = SessionToBooks.Hospital__r.BillingStreet+'<br/>';
                        }
                        if(!String.isEmpty(SessionToBooks.Hospital__r.BillingCity)){
                            BillingCity = SessionToBooks.Hospital__r.BillingCity+'<br/>';
                        }
                        if(!String.isEmpty(SessionToBooks.Hospital__r.BillingCountry)){
                            BillingCountry = SessionToBooks.Hospital__r.BillingCountry+'<br/>';
                        }
                        if(!String.isEmpty(SessionToBooks.Procedures__c)){
                            Procedures = SessionToBooks.Procedures__c;
                        }
                        if(SessionToBooks.Medical_Balance__c != null){
                            Balance = SessionToBooks.Medical_Balance__c;
                        }
                        
                        //LineItems.Program_Itinerary_Info__c = BillingStreet+BillingCity+BillingCountry;
                        LineItems.Program_Itinerary_Info__c = 'Surgery';
                       	LineItems.Program_Itinerary_Details__c = Procedures+'<br/>'+ SessionToBooks.Doctor__r.FirstName+' '+SessionToBooks.Doctor__r.LastName+'<br/>'+Balance;
                        LineItems.Itenrary_Items__c = BookToIts.get(ComingIts.Booking__c);
                        LineItemsToCreate.add(LineItems);
                    }
                }
                // ======== >>>> Get Line Items <<<< ==========
                ItenraryId = BookToIts.get(ComingIts.Booking__c);
                // ============================================
            }
        //} catch (Exception e){
            //throw new AuraHandledException('Error Message' + e.getMessage()+e.getStackTraceString());
        //}
        
        if(LineItemsToCreate.size() > 0){
            Insert LineItemsToCreate;
        }
        
        
        System.debug('Created Itenrary Id: '+ItenraryId);
        Integer counter = 1;
        for(Itenrary_Line_Item__c ItsLineItems : [SELECT Name FROM Itenrary_Line_Item__c WHERE Itenrary_Items__c =: ItenraryId ORDER BY Start_Date__c ASC]){
            ItsLineItems.Name = String.valueOf(counter);
            counter++;
            LineItemsToUpdate.add(ItsLineItems);
        }
        if(LineItemsToUpdate.size() > 0){
            Update LineItemsToUpdate;
        }
    }
}