force-app/main/default/objects/Contact/fields/About__c.field-meta.xml
<CustomField>
    <fullName>About__c</fullName>
    <label>About</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profile_Picture__c.field-meta.xml
<CustomField>
    <fullName>Profile_Picture__c</fullName>
    <inlineHelpText>Id of the document in Profile pictures folder</inlineHelpText>
    <label>Profile Picture</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Profile_Picture_Test__c.field-meta.xml
<CustomField>
    <fullName>Profile_Picture_Test__c</fullName>
    <label>Profile Picture Test</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Show_On_Home__c.field-meta.xml
<CustomField>
    <fullName>Show_On_Home__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show On Home</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/OneTeamCtrlTest.cls
@IsTest
public class OneTeamCtrlTest {
    @IsTest static void GetPersonalAssContactsTest(){
        Test.startTest();
            Contact NewTestContact = new Contact();
            NewTestContact.FirstName = 'Test';
            NewTestContact.LastName = 'Contact';
            NewTestContact.Show_On_Home__c = true;
            NewTestContact.Profile_Picture__c = '015O0000003CMEi';
            NewTestContact.Profile_Picture_Test__c = '';
            NewTestContact.About__c = 'Anna joined our team last year as an.';
            Insert NewTestContact;
        	OneTeamCtrl.GetPersonalAssContacts();
        Test.stopTest();
    } 
}